name: omicscope
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pandas
  - numpy
  - scipy
  - python-igraph
  - leidenalg
  - pyarrow       # For parquet support
  - gunicorn      # For web deployment
  - pip:
    - scanpy
    - dash
    - dash-bootstrap-components
    - plotly
    - tqdm        # Added for progress bars